using Longevity.Application.PublicEvidence;
using Npgsql;

namespace Longevity.Infrastructure.PublicEvidence;

public sealed class PostgresMarketIntelligenceCatalog(NpgsqlDataSource dataSource) : IMarketIntelligenceCatalog
{
    public async Task<IReadOnlyList<MarketOfferingSummary>?> ListOfferingsForAssetAsync(string assetSlug, CancellationToken cancellationToken)
    {
        try
        {
            if (!await AssetExistsAsync(assetSlug, cancellationToken)) return null;
            await using var c = dataSource.CreateCommand("SELECT o.id,o.asset_id,a.slug,p.id,p.slug,p.display_name,p.provider_type,p.canonical_website_url,p.primary_region,p.is_active,o.slug,o.display_name,o.offering_type,o.package_quantity::text,o.package_unit,o.billing_cadence,o.is_active FROM market_intelligence.offerings o JOIN public.longevity_assets a ON a.id=o.asset_id JOIN market_intelligence.providers p ON p.id=o.provider_id WHERE a.slug=$1 AND o.is_active ORDER BY o.slug");
            c.Parameters.AddWithValue(assetSlug); var list = new List<MarketOfferingSummary>(); await using var r = await c.ExecuteReaderAsync(cancellationToken); while (await r.ReadAsync(cancellationToken)) list.Add(ReadOffering(r)); return list;
        }
        catch (NpgsqlException ex) { throw new MarketIntelligenceUnavailableException("Market intelligence persistence is unavailable.", ex); }
    }
    public async Task<MarketOfferingDetail?> GetOfferingAsync(Guid offeringId, CancellationToken cancellationToken)
    {
        try { await using var c = dataSource.CreateCommand("SELECT o.id,o.asset_id,a.slug,p.id,p.slug,p.display_name,p.provider_type,p.canonical_website_url,p.primary_region,p.is_active,o.slug,o.display_name,o.offering_type,o.package_quantity::text,o.package_unit,o.billing_cadence,o.is_active,o.provider_product_code,o.canonical_url FROM market_intelligence.offerings o JOIN public.longevity_assets a ON a.id=o.asset_id JOIN market_intelligence.providers p ON p.id=o.provider_id WHERE o.id=$1"); c.Parameters.AddWithValue(offeringId); await using var r = await c.ExecuteReaderAsync(cancellationToken); return await r.ReadAsync(cancellationToken) ? new(ReadOffering(r), r.IsDBNull(17) ? null : r.GetString(17), r.IsDBNull(18) ? null : r.GetString(18), "Latest recorded observations may be stale and are not live price or availability guarantees.") : null; }
        catch (NpgsqlException ex) { throw new MarketIntelligenceUnavailableException("Market intelligence persistence is unavailable.", ex); }
    }
    public async Task<MarketHistoryPage<PriceObservation>?> ListPriceHistoryAsync(Guid offeringId, MarketHistoryQuery query, CancellationToken cancellationToken)
    {
        try { if (!await OfferingExistsAsync(offeringId, cancellationToken)) return null; var rows = await PriceRows(offeringId, query, cancellationToken); var hasNext = rows.Count > query.Limit; if (hasNext) rows.RemoveAt(rows.Count - 1); return new(rows, hasNext ? MarketIntelligenceValidation.Cursor(rows[^1].ObservedAt, rows[^1].Id) : null, query.Limit, hasNext); }
        catch (NpgsqlException ex) { throw new MarketIntelligenceUnavailableException("Market intelligence persistence is unavailable.", ex); }
    }
    public async Task<MarketHistoryPage<AvailabilityObservation>?> ListAvailabilityHistoryAsync(Guid offeringId, MarketHistoryQuery query, CancellationToken cancellationToken)
    {
        try { if (!await OfferingExistsAsync(offeringId, cancellationToken)) return null; var rows = await AvailabilityRows(offeringId, query, cancellationToken); var hasNext = rows.Count > query.Limit; if (hasNext) rows.RemoveAt(rows.Count - 1); return new(rows, hasNext ? MarketIntelligenceValidation.Cursor(rows[^1].ObservedAt, rows[^1].Id) : null, query.Limit, hasNext); }
        catch (NpgsqlException ex) { throw new MarketIntelligenceUnavailableException("Market intelligence persistence is unavailable.", ex); }
    }
    private async Task<bool> AssetExistsAsync(string slug, CancellationToken ct) { await using var c = dataSource.CreateCommand("SELECT 1 FROM public.longevity_assets WHERE slug=$1"); c.Parameters.AddWithValue(slug); return await c.ExecuteScalarAsync(ct) is not null; }
    private async Task<bool> OfferingExistsAsync(Guid id, CancellationToken ct) { await using var c = dataSource.CreateCommand("SELECT 1 FROM market_intelligence.offerings WHERE id=$1"); c.Parameters.AddWithValue(id); return await c.ExecuteScalarAsync(ct) is not null; }
    private static MarketOfferingSummary ReadOffering(NpgsqlDataReader r) => new(r.GetGuid(0), r.GetGuid(1), r.GetString(2), new(r.GetGuid(3), r.GetString(4), r.GetString(5), ParseProviderType(r.GetString(6)), r.IsDBNull(7) ? null : r.GetString(7), r.IsDBNull(8) ? null : r.GetString(8), r.GetBoolean(9)), r.GetString(10), r.GetString(11), ParseOfferingType(r.GetString(12)), r.IsDBNull(13) ? null : r.GetString(13), r.IsDBNull(14) ? null : r.GetString(14), r.IsDBNull(15) ? null : r.GetString(15), r.GetBoolean(16), null);
    private async Task<List<PriceObservation>> PriceRows(Guid id, MarketHistoryQuery q, CancellationToken ct) { var (cursorObservedAt, cursorId) = string.IsNullOrWhiteSpace(q.Cursor) ? (DateTimeOffset.MaxValue, Guid.Parse("ffffffff-ffff-ffff-ffff-ffffffffffff")) : MarketIntelligenceValidation.ParseCursor(q.Cursor); await using var c = dataSource.CreateCommand("SELECT id,offering_id,amount,currency_code,pricing_basis,billing_interval,quantity::text,quantity_unit,geographic_market,observed_at,source_url,source_label,created_at FROM market_intelligence.price_observations WHERE offering_id=$1 AND observed_at >= $2 AND observed_at <= $3 AND (observed_at < $4 OR (observed_at = $4 AND id < $5)) ORDER BY observed_at DESC,id DESC LIMIT $6"); c.Parameters.AddWithValue(id); c.Parameters.AddWithValue(q.StartDate ?? DateTimeOffset.MinValue); c.Parameters.AddWithValue(q.EndDate ?? DateTimeOffset.MaxValue); c.Parameters.AddWithValue(cursorObservedAt); c.Parameters.AddWithValue(cursorId); c.Parameters.AddWithValue(q.Limit + 1); var rows = new List<PriceObservation>(); await using var r = await c.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) rows.Add(new(r.GetGuid(0), r.GetGuid(1), r.GetDecimal(2), r.GetString(3), ParsePricingBasis(r.GetString(4)), r.IsDBNull(5) ? null : r.GetString(5), r.IsDBNull(6) ? null : r.GetString(6), r.IsDBNull(7) ? null : r.GetString(7), r.IsDBNull(8) ? null : r.GetString(8), r.GetFieldValue<DateTimeOffset>(9), r.GetString(10), r.IsDBNull(11) ? null : r.GetString(11), r.GetFieldValue<DateTimeOffset>(12))); return rows; }
    private async Task<List<AvailabilityObservation>> AvailabilityRows(Guid id, MarketHistoryQuery q, CancellationToken ct) { var (cursorObservedAt, cursorId) = string.IsNullOrWhiteSpace(q.Cursor) ? (DateTimeOffset.MaxValue, Guid.Parse("ffffffff-ffff-ffff-ffff-ffffffffffff")) : MarketIntelligenceValidation.ParseCursor(q.Cursor); await using var c = dataSource.CreateCommand("SELECT id,offering_id,availability_status,geographic_market,observed_at,source_url,source_label,created_at FROM market_intelligence.availability_observations WHERE offering_id=$1 AND observed_at >= $2 AND observed_at <= $3 AND (observed_at < $4 OR (observed_at = $4 AND id < $5)) ORDER BY observed_at DESC,id DESC LIMIT $6"); c.Parameters.AddWithValue(id); c.Parameters.AddWithValue(q.StartDate ?? DateTimeOffset.MinValue); c.Parameters.AddWithValue(q.EndDate ?? DateTimeOffset.MaxValue); c.Parameters.AddWithValue(cursorObservedAt); c.Parameters.AddWithValue(cursorId); c.Parameters.AddWithValue(q.Limit + 1); var rows = new List<AvailabilityObservation>(); await using var r = await c.ExecuteReaderAsync(ct); while (await r.ReadAsync(ct)) rows.Add(new(r.GetGuid(0), r.GetGuid(1), ParseAvailabilityStatus(r.GetString(2)), r.IsDBNull(3) ? null : r.GetString(3), r.GetFieldValue<DateTimeOffset>(4), r.GetString(5), r.IsDBNull(6) ? null : r.GetString(6), r.GetFieldValue<DateTimeOffset>(7))); return rows; }
    private static ProviderType ParseProviderType(string value) => value switch { "manufacturer" => ProviderType.Manufacturer, "retailer" => ProviderType.Retailer, "clinic" => ProviderType.Clinic, "laboratory" => ProviderType.Laboratory, "pharmacy" => ProviderType.Pharmacy, "subscription_service" => ProviderType.SubscriptionService, "marketplace" => ProviderType.Marketplace, _ => ProviderType.Other };
    private static OfferingType ParseOfferingType(string value) => value switch { "physical_product" => OfferingType.PhysicalProduct, "subscription" => OfferingType.Subscription, "clinical_service" => OfferingType.ClinicalService, "laboratory_test" => OfferingType.LaboratoryTest, "membership" => OfferingType.Membership, "device" => OfferingType.Device, "software_service" => OfferingType.SoftwareService, _ => OfferingType.Other };
    private static PricingBasis ParsePricingBasis(string value) => value switch { "one_time_purchase" => PricingBasis.OneTimePurchase, "recurring_subscription" => PricingBasis.RecurringSubscription, "per_treatment" => PricingBasis.PerTreatment, "per_test" => PricingBasis.PerTest, "per_visit" => PricingBasis.PerVisit, "per_unit" => PricingBasis.PerUnit, _ => PricingBasis.Other };
    private static AvailabilityStatus ParseAvailabilityStatus(string value) => value switch { "available" => AvailabilityStatus.Available, "out_of_stock" => AvailabilityStatus.OutOfStock, "waitlist" => AvailabilityStatus.Waitlist, "unavailable" => AvailabilityStatus.Unavailable, "discontinued" => AvailabilityStatus.Discontinued, _ => AvailabilityStatus.Unknown };
}
