using Longevity.Application.PublicEvidence;
using Npgsql;
using NpgsqlTypes;

namespace Longevity.Infrastructure.PublicEvidence;

public sealed class PostgresPublicEvidenceCatalog(NpgsqlDataSource dataSource) : IPublicEvidenceCatalog
{
    public async Task<PublicEvidencePage<PublicEvidenceAsset>> ListAssetsAsync(int page, int pageSize, CancellationToken cancellationToken)
    {
        await using var command = dataSource.CreateCommand("SELECT a.id,a.slug,a.name,a.asset_type,a.short_summary, count(DISTINCT c.id)::int, count(DISTINCT ce.source_id)::int FROM public.longevity_assets a LEFT JOIN public.claims c ON c.asset_id=a.id LEFT JOIN public.claim_evidence ce ON ce.claim_id=c.id GROUP BY a.id ORDER BY a.slug LIMIT $1 OFFSET $2");
        command.Parameters.AddWithValue(pageSize + 1); command.Parameters.AddWithValue((page - 1) * pageSize);
        var items = new List<PublicEvidenceAsset>(); await using var reader = await command.ExecuteReaderAsync(cancellationToken);
        while (await reader.ReadAsync(cancellationToken)) items.Add(new(reader.GetGuid(0), reader.GetString(1), reader.GetString(2), reader.GetString(3), reader.IsDBNull(4) ? null : reader.GetString(4), reader.GetInt32(5), reader.GetInt32(6)));
        var hasNext = items.Count > pageSize; if (hasNext) items.RemoveAt(items.Count - 1); return new(items, page, pageSize, hasNext);
    }
    public async Task<PublicEvidenceAssetDetail?> GetAssetAsync(string slug, CancellationToken cancellationToken) { var asset = await LoadAssetAsync(slug, cancellationToken); return asset is null ? null : new(asset, await LoadClaimsAsync(asset.Id, cancellationToken)); }
    public async Task<IReadOnlyList<PublicEvidenceClaim>?> ListClaimsAsync(string slug, CancellationToken cancellationToken) { var asset = await LoadAssetAsync(slug, cancellationToken); return asset is null ? null : await LoadClaimsAsync(asset.Id, cancellationToken); }
    public async Task<PublicEvidenceClaim?> GetClaimAsync(Guid claimId, CancellationToken cancellationToken) { await using var command = dataSource.CreateCommand("SELECT c.id,c.asset_id,c.claim_text,c.claim_type,c.target_system,c.evidence_score,c.hype_score,c.risk_score,c.plain_english_verdict,count(ce.id)::int FROM public.claims c LEFT JOIN public.claim_evidence ce ON ce.claim_id=c.id WHERE c.id=$1 GROUP BY c.id"); command.Parameters.AddWithValue(claimId); await using var r=await command.ExecuteReaderAsync(cancellationToken); if(!await r.ReadAsync(cancellationToken)) return null; var claim=await ReadClaimAsync(r,cancellationToken); return claim with { Evidence = await LoadEvidenceAsync(claim.Id,cancellationToken) }; }
    private async Task<PublicEvidenceAsset?> LoadAssetAsync(string slug,CancellationToken ct){await using var c=dataSource.CreateCommand("SELECT a.id,a.slug,a.name,a.asset_type,a.short_summary,count(DISTINCT cl.id)::int,count(DISTINCT ce.source_id)::int FROM public.longevity_assets a LEFT JOIN public.claims cl ON cl.asset_id=a.id LEFT JOIN public.claim_evidence ce ON ce.claim_id=cl.id WHERE a.slug=$1 GROUP BY a.id");c.Parameters.AddWithValue(slug);await using var r=await c.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetInt32(5),r.GetInt32(6)):null;}
    private async Task<IReadOnlyList<PublicEvidenceClaim>> LoadClaimsAsync(Guid assetId,CancellationToken ct){await using var c=dataSource.CreateCommand("SELECT c.id,c.asset_id,c.claim_text,c.claim_type,c.target_system,c.evidence_score,c.hype_score,c.risk_score,c.plain_english_verdict,count(ce.id)::int FROM public.claims c LEFT JOIN public.claim_evidence ce ON ce.claim_id=c.id WHERE c.asset_id=$1 GROUP BY c.id ORDER BY c.id");c.Parameters.AddWithValue(assetId);await using var r=await c.ExecuteReaderAsync(ct);var list=new List<PublicEvidenceClaim>();while(await r.ReadAsync(ct)){var claim=await ReadClaimAsync(r,ct);list.Add(claim with { Evidence=await LoadEvidenceAsync(claim.Id,ct) });}return list;}
    private async Task<IReadOnlyList<PublicEvidenceItem>> LoadEvidenceAsync(Guid claimId,CancellationToken ct){await using var c=dataSource.CreateCommand("SELECT ce.id,ce.source_id,ce.evidence_direction,ce.evidence_level,ce.population,ce.outcome_measured,ce.effect_summary,ce.limitations,ce.relevance_score,s.source_type,s.title,s.url,s.publication_name,s.published_date,s.doi,s.pmid,s.trial_id,s.source_quality_score FROM public.claim_evidence ce JOIN public.sources s ON s.id=ce.source_id WHERE ce.claim_id=$1 ORDER BY ce.id");c.Parameters.AddWithValue(claimId);await using var r=await c.ExecuteReaderAsync(ct);var list=new List<PublicEvidenceItem>();while(await r.ReadAsync(ct)){var source=new PublicEvidenceSource(r.GetGuid(1),r.GetString(9),r.GetString(10),r.IsDBNull(11)?null:r.GetString(11),r.IsDBNull(12)?null:r.GetString(12),r.IsDBNull(13)?null:r.GetFieldValue<DateOnly>(13),r.IsDBNull(14)?null:r.GetString(14),r.IsDBNull(15)?null:r.GetString(15),r.IsDBNull(16)?null:r.GetString(16),r.IsDBNull(17)?null:r.GetDecimal(17));list.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetString(6),r.IsDBNull(7)?null:r.GetString(7),r.IsDBNull(8)?null:r.GetDecimal(8),source));}return list;}
    private static Task<PublicEvidenceClaim> ReadClaimAsync(NpgsqlDataReader r,CancellationToken ct)=>Task.FromResult<PublicEvidenceClaim>(new(r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.IsDBNull(5)?null:r.GetDecimal(5),r.IsDBNull(6)?null:r.GetDecimal(6),r.IsDBNull(7)?null:r.GetDecimal(7),r.IsDBNull(8)?null:r.GetString(8),r.GetInt32(9),[]));
}
